# Generated by Django 5.1.3 on 2024-11-09 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookHub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='page',
            field=models.IntegerField(default=0),
        ),
    ]
