# Generated by Django 5.1.3 on 2024-11-12 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookHub', '0004_alter_book_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChekDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateTimeField(auto_now_add=True)),
                ('count_of_read_pages', models.IntegerField(default=0)),
            ],
        ),
    ]
